### ISSUE TITLE
Payment instruments not supported by proposal

### ISSUE THREAD

**Issue by zkoch** [WICG/paymentrequest#10]
This proposal is biased towards standard ways of paying in US/Europe. Are there payment instruments or schemes out there (e.g. Alipay?) that wouldn't work under this model? Would like to start a discussion around these and figure out if/how the proposal needs to be modified to address other critical use cases.

**Comment by mattsaxon** [comment]
Zach, the intention of the Payment Flows task force is to uncover exactly this sort of issue. AliPay is one of the flows targeted to model.

**Comment by hober** [comment]
I think the current proposal is incompatible with PassKit, surprisingly.

(In a super minor way which I will describe in a new issue.)

**Comment by adrianba** [comment]
I recommend closing this general purpose issue because, as @mattsaxon says, the work in the Web Payments WG to document [payment flows](https://github.com/w3c/webpayments/wiki/Flows) should hopefully uncover problems with the model. We should open issues for specific problems as we uncover them (like @hober did for the PassKit issue #23.

**Comment by zkoch** [comment]
Agreed.
