### ISSUE TITLE
Overridng Common Payment Instruments

### ISSUE THREAD

**Issue by mattsaxon** [WICG/paymentrequest#21]
In the spec, the supportedInstruments array has a mix of domain names ("bobpay.com") and names ("visa"). How will it be possible for visa to provide an overridden payment instrument at "visa.com". Or is it expect that the merchant will have to explicitly state that they accept "visa.com" aswell as "visa"?

Can I suggest that the example between ‘Basic Flow’ and ‘Registration Payment Instruments’ is refined to show how match up is done, so for example is ‘url’ in ‘payment_instrument’ registration the field  that is mapped against the ‘supportedInstruments’ array. How would this work for the non-domain values such as Visa and BitCoin?

**Comment by zkoch** [comment]
Good question. Yes, presumably it would be "visa" and "visa.com" (or perhaps something like "visa.com/verified"). So yes, I think the Merchant is going to have to declare that they support standard, non-special Visa PANs as well as Visa's official checkout solution or similar.

Happy to clarify this in the next iteration. But yes, the idea here is that URLs are used because they allow us to match things easily. The exception, of course, being any payment scheme that we wish to special case. I'm not sure bitcoin is worth that effort currently, but probably is for Visa, MC, etc

**Comment by webpayments** [comment]
*** NOTE: ***

    Your message was sent from an address which is not on the list
    of people who are authorized to post to this mailing list.
    Therefore, your message has been forwarded to the list maintainer
    for manual processing.

    If you do not see your message appear on the list or in the
    mailing list archives within a few business days, you may wish
    to contact the mailing list maintainer to investigate the delay.

    -- W3C Postmaster
       http://www.w3.org/Mail/

your message follows:
----------------------------------------------------------------------------


----==_mimepart_564916301684e_a383fc3973c12bc229953c
Content-Type: text/plain;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

Good question. Yes, presumably it would be "visa" and "visa.com" (or perhaps something like "visa.com/verified"). So yes, I think the Merchant is going to have to declare that they support standard, non-special Visa PANs as well as Visa's official checkout solution or similar.

Happy to clarify this in the next iteration. But yes, the idea here is that URLs are used because they allow us to match things easily. The exception, of course, being any payment scheme that we wish to special case. I'm not sure bitcoin is worth that effort currently, but probably is for Visa, MC, etc

---
Reply to this email directly or view it on GitHub:
https://github.com/WICG/paymentrequest/issues/21#issuecomment-156869306
----==_mimepart_564916301684e_a383fc3973c12bc229953c
Content-Type: text/html;
 charset=UTF-8
Content-Transfer-Encoding: 7bit

<p>Good question. Yes, presumably it would be "visa" and "visa.com" (or perhaps something like "visa.com/verified"). So yes, I think the Merchant is going to have to declare that they support standard, non-special Visa PANs as well as Visa's official checkout solution or similar.</p>

<p>Happy to clarify this in the next iteration. But yes, the idea here is that URLs are used because they allow us to match things easily. The exception, of course, being any payment scheme that we wish to special case. I'm not sure bitcoin is worth that effort currently, but probably is for Visa, MC, etc</p>

<p style="font-size:small;-webkit-text-size-adjust:none;color:#666;">&mdash;<br>Reply to this email directly or <a href="https://github.com/WICG/paymentrequest/issues/21#issuecomment-156869306">view it on GitHub</a>.<img alt="" height="1" src="https://github.com/notifications/beacon/APFrHIzG0gp15ziHiejOJrxRFyEYOVdMks5pGQ2wgaJpZM4GiVbX.gif" width="1" /></p>
<div itemscope itemtype="http://schema.org/EmailMessage">
<div itemprop="action" itemscope itemtype="http://schema.org/ViewAction">
  <link itemprop="url" href="https://github.com/WICG/paymentrequest/issues/21#issuecomment-156869306"></link>
  <meta itemprop="name" content="View Issue"></meta>
</div>
<meta itemprop="description" content="View this Issue on GitHub"></meta>
</div>

----==_mimepart_564916301684e_a383fc3973c12bc229953c--

**Comment by mattsaxon** [comment]
I'm happy that the merchant would need to specify the support for "Verified by Visa" as you say, however I'm asking about the case where an instrument was to provided to override the default processing you are suggesting for Visa, MC and other card payments. I'm not very comfortable with Visa, MC etc. being a special cases as I think there may well be others. The way the CG proposal deal with this is by allowing the merchant to specify the processing endpoint. This to be appears more generic to me.

**Comment by zkoch** [comment]
I'm not sure I understand. We don't offer any processing. That's a key part of the proposal. The proposal talks about standardizing two things: 1.) Ubiquitous payment schemes (e.g. "Visa", "Mastercard"), primarily to support the legacy case and that most websites process credit card payments; and 2.) Standardizing the format in which these responses are returned. So if a merchant accepts "Visa", and a "Visa" response comes back, that response should look the same no matter who is providing it.

**Comment by mattsaxon** [comment]
But there is the opportunity for payment processing (e.g. authorisation or push) to occur inside the payment instrument. You are proposing no processing for cards, but how might that change in the future? For example a reasonable use case it to tokenise the card details prior to sending onto the merchant, the current proposal allows extension for the non-standard payment instruments via the registration process, but not for cards. The only way I could see this occurring in the flow as stands is by defining a new payment type, e.g. CardToken.com. This would have a number of issues associated with it, not least the inability to use the card numbers in the (browser) wallet.

**Comment by adrianba** [comment]
I think the confusion here is that bobspay.com wasn't intended to be detected as a domain name. The idea was to suggest something branded that way.

It will be the job of the [payment method identifiers specification](http://wicg.github.io/paymentrequest/specs/method-identifiers.html) to describe what the strings should actually look like and if we will support short strings like "visa" or require something related to "visa.com".

**Comment by zkoch** [comment]
I actually did intend for bobpay.com to be a domain name. :) I still think, apart from ubiquitous payment schemes like credit cards, domains are the best tool to use (combined with app manifest files).

**Comment by adrianba** [comment]
> I actually did intend for bobpay.com to be a domain name. :) I still think, apart from ubiquitous payment schemes like credit cards, domains are the best tool to use (combined with app manifest files). 

Okay, in that case I think we need to be clear how you detect this. I also think bobspay.com needs to be able to support more than one version of a payment method.

**Comment by msporny** [comment]
> domains are the best tool to use (combined with app manifest files)

I don't necessarily disagree with the first statement, but I'd like to understand why you think app manifest files are the best path forward wrt. registration of payment methods? Why not a programmatic register/query mechanism?

**Comment by adrianba** [comment]
This issue is about the coordination of well-known identifies, if we support them. This is tracked by w3c/browser-payment-api#10 (and w3c/browser-payment-api#11). It also touches on how registration will be handled, which is tracked by w3c/browser-payment-api#12.
