### ISSUE TITLE
Use navigator.payments rather than creating a new object instance

### ISSUE THREAD

**Issue by adrianhopebailie** [WICG/paymentrequest#42]
@dlongley has provided some well thought out analysis of the API shape here: https://github.com/w3c/webpayments/issues/41#issuecomment-165487997

Based on this I would suggest changing the API to work more like the new `fetch()` API, although I'd recommend namespacing the functions under `navigator.payments`.

This is related to #41 in that it also proposes a different method signature.

```javascript
    //Processing instructions for the payment mediator
    var myOptions = {
        validateRequest: true,
        requestSignature: { //Example from https://tools.ietf.org/html/rfc7520#section-4.3.3
            "payload": "SXTigJlzIGEgZGFuZ2Vyb3VzIGJ1c2luZXNzLCBGcm9kbywg" +
                "Z29pbmcgb3V0IHlvdXIgZG9vci4gWW91IHN0ZXAgb250byB0aGUgcm9h" +
                "ZCwgYW5kIGlmIHlvdSBkb24ndCBrZWVwIHlvdXIgZmVldCwgdGhlcmXi" +
                "gJlzIG5vIGtub3dpbmcgd2hlcmUgeW91IG1pZ2h0IGJlIHN3ZXB0IG9m" +
                "ZiB0by4",
            "protected": "eyJhbGciOiJFUzUxMiIsImtpZCI6ImJpbGJvLmJhZ2dpbn" +
                "NAaG9iYml0b24uZXhhbXBsZSJ9",
            "signature": "AE_R_YZCChjn4791jSQCrdPZCNYqHXCTZH0-JZGYNlaAjP" +
                "2kqaluUIIUnC9qvbu9Plon7KRTzoNEuT4Va2cmL1eJAQy3mtPBu_u_sD" +
                "DyYjnAMDxXPn7XrT0lw-kvAD890jl8e2puQens_IEKBpHABlsbEPX6sF" +
                "Y8OcGDqoRuBomu9xQ2"
        },
        encryptResponse: {
            responseEncryptionAlgorithm: "AES-CBC",
            publicKey: 'https://merchant.com/keys/12'
        }};

    //Payment request data that is passed to the payment app
    // This is an array of request variations indexed by
    // payment method identifiers
    var myRequest = [
        {
            methods: ["https://paypal.com/"],
            details: {}, //Details of the offer
            data: {}, //Payment method specific data
        },
        {
            methods: ["https://bitcoin.org/"],
            details: {}, //Details of the offer
            data: {}, //Payment method specific data
        }
    ];

    //This API shape still supports events if required
    navigator.payments.addEventListener("optionsChange", function (changeEvent) {
        if(changeEvent.optionGroup == "shipping")
        {
            // Process shipping options change and update amounts

        }
    });
    
    
    //Request a payment
    navigator.payments.requestPayment(myRequest, myoptions)
            .then(function(response) {
                switch (response.method)
                {
                    case "https://paypal.com/":
                        //Process PayPal response
                        break;
                    
                    case "https://bitcoin.org/":
                        //Process Bitcoin response
                        break;
                };
            });
```
As I have suggested in https://github.com/w3c/webpayments/issues/41 you could add a `getShippingAddress()` method that could, in the long term, be a shortcut to a generic credentials request.

```javascript
navigator.payments.getShippingAddress().then(
            function(address) {
                if (!address)
                //We'll have to get the address through the website UI
                // so close the dialogue that's currently waiting for us to
                // submit another request
                navigator.payments.closeDialogue();

                //Build request based on supplied address
                // i.e. with appropriate shipping options
  ```

**Comment by adrianba** [comment]
This issue mixes a number of questions:

1. Should events or Promises be used in the API?
2. Should PaymentRequest constructor or `navigator.paymentrequest` singleton be used?
3. Is the PaymentRequest proposal too high level? Should shipping address be removed from the PaymentRequest flow because it is doing too much?
4. Should shipping address be available as a separate `getShippingAddress()` method?

Here are my thoughts on each of these.

1. Events are used when something may happen multiple times. Promises can only be resolved once. We've tried to use Promises where they make sense and to use events where they may be fired multiple times. Reading between the lines, there's a suggestion that `updatePaymentRequest()` could accept a Promise wrapping the asynchronous work the page wants to do (the suggestion was to "allow the merchant website to provide hooks that may return promises"). That's something worth considering, especially if we believe most sites will need to do something asynchronous in response to the event.

2. I don't yet understand the proposal to change to use a `navigator.paymentrequest` singleton. One reason we went with the constructor approach is that the object has a well-defined linear life cycle from `created` to `closed` and it is much simpler to not have to worry about re-using objects for different payment operations.

3. This is a complex issue and a key one that we need to discuss and solve.
In general, the extensible web approach is to build low level APIs and to allow web developers to build higher level experiences using HTML/CSS/JavaScript. However, APIs that deal with privacy sensitive data (such as addresses) and privileged operations (such as making a payment) need to ensure that users understand and consent to the operations. Understanding and consenting to many low-level operations is difficult to do without confusing and annoying the user. At the same time, payment operations will likely differ significantly between different operating environments and different form factors. The user agent may well have to orchestrate multiple third-party payment applications.
This creates a tension and it is for this reason that we're promoting the idea of incubating different ideas to try to get some experience of what works well before deciding. The PaymentRequest proposal argues for a higher-level domain-specific API that allows the user agent to coordinate the different parts of the request with the goal of creating a smoother checkout flow. It remains to be seen if this will be the best option and we need more experimentation and discussion.

4. With the current API proposal it is possible to make a PaymentRequest and not use the shipping address option. It is interesting to consider whether we should also make the opposite possible so that merchants who want to build a more linear flow where they ask for shipping details independent from payment could still use the API.

**Comment by bifurcation** [comment]
I think there's a missing distinction here between *how* you're willing to be paid and *what* you want to be paid.  The former question is the one that the user needs to be involved in, and it has a very clear event model -- you request a payment provider with some bounds, and the user hands you one.  Then you request what you want from that provider.

```
var how = { /* how am i willing to be pad? */ };
var what = { /* what do i want to be paid? */ };
navigator.payment.getProvider(how)
.then(provider => provider.requestPayment(what));
```

This also lets us reflect all these questions around different payment schemes, shipping addresses, etc. in the type system for what's returned by `getProvider()`.  The top-level `PaymentProvider` interface might only have the `requestPayment()` method, but you could have sub-interfaces that define more nuanced interactions, or expose additional capabilities (`if (provider.shippingAddress) ...`).

This also aligns pretty cleanly with the idea of registration and delegated payment.  When you register a payment provider, you need to provide the browser what it needs to fulfill the `PaymentProvider` interface.

**Comment by adrianhopebailie** [comment]
@adrianba 

> This issue mixes a number of questions:

Yes, happy to split them out if you like but they seem linked/dependent and worth addressing together.

> Should events or Promises be used in the API?

The API will use only Promises or both Promises and Events.

I think we are mostly in agreement that the website should call an API,  supplying a payment request, and in return will get a promise that resolves to the final payment response.

At this point the website no longer has focus so it can do some asynch processing but nothing that requires user interaction.

Which begs the question, do we need events at all? That will be implicitly answered by addressing https://github.com/w3c/webpayments/issues/55

i.e. Are there interactions with the browser or payment app that will require the website to update the payment request? _(Getting the shipping address is an example of one but whether that is included in the payment request is still under debate -- my point about these being linked issues)_

If not, why complicate the interaction with the API using events. Why does the website need to track the state of the payment request at all? As discussed in the issue above there are pros and cons to both approaches (having and not having events) and I suggest we look at the flows and use cases to determine which is best.

> Should PaymentRequest constructor or navigator.paymentrequest singleton be used?

There is a third option, use the PaymentRequest object but don't provide the payment details in the constructor. My strongest objection to the proposed pattern is that the website must instantiate the payment request at a time when it may not have all the data it requires. Where possible we should make it easy for the website to _prepare_ the payment request and gather all of the data required to do this before _making_ the payment request.

My argument in favour of using a static (or singleton) `payments` object that is an attribute of the `navigator` is that I don't foresee the website ever having multiple payments requests in flight at the same time (or put another way, ever instantiating multiple PaymentRequest objects).

The UI pattern that has been proposed precludes this from happening unless the payment can be executed without the website losing focus (i.e. the payment app can process the payment without needing input AND we support this pattern - seems challenging on mobile).
 
> the object has a well-defined linear life cycle from created to closed

This seems like an argument in favour of using a static object.

As has been pointed out by a few members already the proposed pattern is very similar to `XMLHttpRequest` which has been much maligned for how hard it is to use and has now been replaced with `fetch` as a result.

Most crucially though, the fact that we intend to take focus away from the website during this linear flow suggests that complex asynchronous operations will not be possible, in as much as they will not be able to do anything that requires UI.

Designing an API that provides a mechanism for the website to update the payment request during the life-cycle of the payment places complex requirements on the deployment environment. Flexibility introduces complexity but the current proposal seems to introduce the complexity without providing any additional flexibility.

> Is the PaymentRequest proposal too high level? Should shipping address be removed from the PaymentRequest flow because it is doing too much?

and

> Should shipping address be available as a separate getShippingAddress() method?

I am in favour of moving (not removing) the ability to get a shipping address but there is already a long thread discussing this here: https://github.com/w3c/webpayments/issues/39

@bifurcation 

We can't provide websites with an API that allows them to farm data from users about what payment methods they have available.

The current design is intended to place the user agent (mediator - see the [component architecture](https://github.com/w3c/webpayments/wiki/A-Payments-Initiation-Architecture-for-the-Web)) in between the website and the user to protect the user's privacy.

**Comment by dlongley** [comment]
@adrianba,

> Events are used when something may happen multiple times. Promises can only be resolved once.

While that is a difference between events and promises, I do not think it's the most important one. Events are used to observe or react to an external process that you don't have control over; when there is no imperative API for asserting control. An event API makes a lot of sense for stream based systems, for example, where there is an external I/O process and you want to capture some incoming data or other kinds of events -- but you don't directly control the transfer of that incoming information.

Promises are merely an asynchronous analog for imperative synchronous programming. When you make an imperative call, you pass some parameters and get a result. A Promise just lets you do this asynchronously; the result is returned to you at some later point in time through the resolution of the Promise. The caller is in control.

The problem I have with the paymentrequest API is that control over the payments process is turned over *too soon*. The merchant website should have complete control over how to structure its own payment request, but it loses some of that control by handing over an "incomplete" payment request to get things started. Since the site has more to say before the payment request is actually ready, this introduces a need in the API to allow the merchant site to wrestle some of that control back. This is currently implemented by combining a synchronous event system, which I believe is a tool for a different kind of job.

The problem with this design becomes immediately apparent when the merchant site decides they need to do some asynchronous process in order to properly control the payment request. They can't do this with a synchronous event system, so now control needs to be handed back to the merchant site anyway, by pausing further processing until an imperative call is made by the site. This is a good indication that the API is too prescriptive and will lead to frustration or the leakage of further implementation details such as state information that the merchant site should not need to deal with at all.

All of this indicates to me that we should completely separate different composable parts of the flow (separation of concerns, simpler, lower-level API). Now, there is a concern over keeping the user experience simple as well. But I think the way to do that would be to keep the control in the merchant site -- but make it so the merchant site can "start a flow" and then make the related API calls they want to make to modify the flow and move it along as the merchant sees fit. This makes the browser bits act as if they are receiving events *from the merchant site* instead of the other way around. That seems like the correct approach to me and it removes the complexity from the merchant site.

**Comment by adrianba** [comment]
This is now tracked at w3c/browser-payment-api#16.
