### ISSUE TITLE
Payment instrument installation is platform-dependent

### ISSUE THREAD

**Issue by dbaron** [WICG/paymentrequest#5]
The explainer doc currently says that "Payment instrument installation is platform-dependent"; this is bad as it proposes a Web standard that will only work on some platforms.  Instead, the specification should define a mechanism for payment instrument installation so that it is standardized.

**Comment by zkoch** [comment]
The point I was trying to get at with that is that different platforms may have different requirements for what form the payment instruments will need to take. For example, on mobile operating systems, the right format for that may be a native app. But while the form the payment instrument may take could vary on a platform-by-platform level, we could standardize (at least, as much as is possible) the method through which the browser discovers the right place to install those instruments. That's what we were driving at a bit with the Manifest file.

That said, I am very interested in standardizing a way for payment instruments to be integrated more directly into the browser. This could work very well for desktop. One idea for this is to embed an iFrame inside some sort of native UI and then communicate via standard postMessage. This is what the "embed_url" would point to in the Manifest example in the explainer doc.

Very open to any other thoughts or suggestions you have here on how to accomplish any of this.

**Comment by adrianba** [comment]
I think it is interesting to consider how this will work but I'm not convinced this will be feasible for a simple v1 spec. The payment instruments operate in the context of the user agent and making this aspect interoperable is a much bigger undertaking, desirable but difficult.

**Comment by adrianhopebailie** [comment]
Somewhat related to: https://github.com/w3c/webpayments/issues/26
(We should consider closing one of these issues)

My suggestion is that we consider the minimum data requirements for registration/installation of a payment app (not a payment instrument) and as a minimum allow websites to request installation of a payment app via the API by supplying that information to a a function like `navigator.payments.registerPaymentApp(...)`.

A call to this API would result in a user prompt to allow the UA to install the payment app. 

On a mobile device, if the user accepts, this could result in the mobile OS appstore getting focus and loading the details of the app that the user wishes to install.

On a desktop device, if the user accepts, this could result in the UA fetching the details of the app from a manifest or similar machine-readable document and registering the payment app in the payment mediator's registered apps database.

What is essential is that the app provide a human-readable name, an icon and the set of payment methods it supports so that when a payment request is received the payment mediator is able to determine if the app can be used to process the request and then to provide the user with a useful app selection dialogue.

This is already implicit in the mobile platform/app pattern but will require some work from desktop browsers to design the payment mediator.

It will also be essential that apps are able to notify the payment mediator if the set of payment methods they support changes.

This can easily be achieved on mobile through app updates but it remains to be discussed how and when a similar process could be achieved on desktop.

**Comment by ianbjacobs** [comment]
Is this a job for WebWorkers? 
 http://www.w3.org/TR/workers/

**Comment by adrianba** [comment]
Now tracked by w3c/browser-payment-api#8.
